apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-camel-quarkus-soap
spec:
  pipelineRef:
    name: camel-quarkus-soap
  workspaces:
  - name: source-folder
    persistentVolumeClaim:
      claimName: maven-repo-pvc
